version: '3'

services:
  jmeter:
    build:
      context: .
      dockerfile: jmeter.dockerfile
    volumes:
      - ./jmeter_data:/app/jmeter_scripts
    networks:
      - network
    command: ["jmeter", "-n", "-t", "/app/jmeter_scripts/test.jmx", "-l", "/app/jmeter_scripts/test_results.jtl"]

  server:
    build:
      context: .
      dockerfile: mock.dockerfile
    ports:
      - "8000:8000"
    environment:
      - SERVER_HOST=${SERVER_HOST:-0.0.0.0}
      - SERVER_PORT=8000
    networks:
      - network

volumes:
  config:

networks:
  network:
    driver: bridge
